// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/docs/.dumi/pages/theme-editor-cn/index.ts?type=frontmatter';
import { frontmatter as fm1 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/docs/.dumi/pages/theme-editor/index.tsx?type=frontmatter';
import { frontmatter as fm2 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/docs/.dumi/pages/index-cn/index.ts?type=frontmatter';
import { frontmatter as fm3 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/docs/.dumi/pages/index/index.tsx?type=frontmatter';
import { frontmatter as fm4 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/docs/_docs/react/contributing.en-US.md?type=frontmatter';
import { frontmatter as fm5 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/docs/_docs/react/contributing.zh-CN.md?type=frontmatter';
import { frontmatter as fm6 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/docs/_docs/react/introduce.en-US.md?type=frontmatter';
import { frontmatter as fm7 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/docs/_docs/react/introduce.zh-CN.md?type=frontmatter';
import { frontmatter as fm8 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/packages/core/src/components/button/README.md?type=frontmatter';
import { frontmatter as fm9 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/packages/core/src/components/config-provider/index.en-US.md?type=frontmatter';
import { frontmatter as fm10 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/packages/core/src/components/config-provider/index.zh-CN.md?type=frontmatter';
import { frontmatter as fm11 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/packages/core/src/components/my-component/README.md?type=frontmatter';
import { frontmatter as fm12 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/packages/core/src/components/wave/README.md?type=frontmatter';
import { frontmatter as fm13 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/docs/CHANGELOG.zh-CN.md?type=frontmatter';
import { frontmatter as fm14 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/docs/CHANGELOG.en-US.md?type=frontmatter';

export const filesFrontmatter = {
  'theme-editor-cn/index': fm0,
  'theme-editor/index': fm1,
  'index-cn/index': fm2,
  'index/index': fm3,
  '_docs/react/contributing.en-US': fm4,
  '_docs/react/contributing.zh-CN': fm5,
  '_docs/react/introduce.en-US': fm6,
  '_docs/react/introduce.zh-CN': fm7,
  'components/button/README': fm8,
  'components/config-provider/index.en-US': fm9,
  'components/config-provider/index.zh-CN': fm10,
  'components/my-component/README': fm11,
  'components/wave/README': fm12,
  'changelog-cn': fm13,
  'changelog': fm14,
}
