// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from '/Users/liuzhiwei/Desktop/workspeace/git-code/ikun-design/node_modules/.pnpm/dumi@2.3.0-alpha.9_@babel+core@7.23.3_@types+node@20.10.0_@types+react@18.2.38_eslint@8.54.0__ujnxanr2wquue6vmas34skp7we/node_modules/dumi/dist/client/theme-api/index.js';
export { getRouteMetaById } from './meta/route-meta';
export { loadFilesMeta } from './meta/search';
export { getDemoScopesById } from './live/demo-scopes';
